// Code generated by protoc-gen-go. DO NOT EDIT.
// source: company.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Title struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Title) Reset()         { *m = Title{} }
func (m *Title) String() string { return proto.CompactTextString(m) }
func (*Title) ProtoMessage()    {}
func (*Title) Descriptor() ([]byte, []int) {
	return fileDescriptor_ade57ca5b8f3903f, []int{0}
}

func (m *Title) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Title.Unmarshal(m, b)
}
func (m *Title) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Title.Marshal(b, m, deterministic)
}
func (m *Title) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Title.Merge(m, src)
}
func (m *Title) XXX_Size() int {
	return xxx_messageInfo_Title.Size(m)
}
func (m *Title) XXX_DiscardUnknown() {
	xxx_messageInfo_Title.DiscardUnknown(m)
}

var xxx_messageInfo_Title proto.InternalMessageInfo

func (m *Title) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Title) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Title                *Title   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ade57ca5b8f3903f, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetTitle() *Title {
	if m != nil {
		return m.Title
	}
	return nil
}

type Company struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                *User    `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	CoOwner              *User    `protobuf:"bytes,3,opt,name=coOwner,proto3" json:"coOwner,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Company) Reset()         { *m = Company{} }
func (m *Company) String() string { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()    {}
func (*Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_ade57ca5b8f3903f, []int{2}
}

func (m *Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Company.Unmarshal(m, b)
}
func (m *Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Company.Marshal(b, m, deterministic)
}
func (m *Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Company.Merge(m, src)
}
func (m *Company) XXX_Size() int {
	return xxx_messageInfo_Company.Size(m)
}
func (m *Company) XXX_DiscardUnknown() {
	xxx_messageInfo_Company.DiscardUnknown(m)
}

var xxx_messageInfo_Company proto.InternalMessageInfo

func (m *Company) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Company) GetOwner() *User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Company) GetCoOwner() *User {
	if m != nil {
		return m.CoOwner
	}
	return nil
}

func (m *Company) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*Title)(nil), "protocol.Title")
	proto.RegisterType((*User)(nil), "protocol.User")
	proto.RegisterType((*Company)(nil), "protocol.Company")
}

func init() {
	proto.RegisterFile("company.proto", fileDescriptor_ade57ca5b8f3903f)
}

var fileDescriptor_ade57ca5b8f3903f = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x4f, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x25, 0x4d, 0xd2, 0xb4, 0x27, 0x4d, 0xfb, 0x71, 0x3f, 0x17, 0x41, 0x50, 0x4a, 0x44, 0x70,
	0x15, 0xb0, 0x6e, 0x04, 0x37, 0x12, 0x1f, 0x40, 0x08, 0xba, 0x71, 0x53, 0x62, 0x3a, 0xc2, 0x40,
	0x92, 0x09, 0x99, 0xa8, 0xe8, 0xd2, 0x77, 0x12, 0x7c, 0x3c, 0x6f, 0x67, 0x1a, 0xec, 0x42, 0xdc,
	0x64, 0x6e, 0xce, 0x3d, 0x7f, 0x17, 0x51, 0xa9, 0xea, 0xb6, 0x68, 0xde, 0xd2, 0xb6, 0x53, 0xbd,
	0xa2, 0x89, 0x79, 0x4a, 0x55, 0x1d, 0x46, 0xaa, 0xed, 0xa5, 0x6a, 0xb4, 0x5d, 0x24, 0xd7, 0xf0,
	0xef, 0x64, 0x5f, 0x09, 0x3a, 0xc1, 0x48, 0x6e, 0x62, 0x67, 0xe9, 0x9c, 0xb9, 0xd9, 0xff, 0x8f,
	0xcf, 0x78, 0x81, 0x88, 0x19, 0x4f, 0x42, 0x6b, 0x66, 0xaf, 0xe5, 0x26, 0xe7, 0x35, 0x11, 0xbc,
	0xa6, 0xa8, 0x45, 0x3c, 0x62, 0xda, 0x34, 0x37, 0x73, 0xf2, 0x02, 0xef, 0x5e, 0x8b, 0x8e, 0x8e,
	0xf6, 0x0c, 0x22, 0x36, 0x98, 0x22, 0x78, 0x66, 0xfc, 0x0f, 0x29, 0x1d, 0xc0, 0x17, 0x75, 0x21,
	0xab, 0xd8, 0x35, 0xa0, 0xfd, 0xa1, 0x53, 0xf8, 0xfd, 0xb6, 0x52, 0xec, 0x31, 0x1a, 0xae, 0x16,
	0xe9, 0xd0, 0x3d, 0x35, 0x4d, 0x73, 0xbb, 0x4d, 0xbe, 0x1c, 0x04, 0x37, 0xf6, 0x48, 0x5a, 0xee,
	0x65, 0xff, 0xe3, 0xec, 0x19, 0xb0, 0xbb, 0x7f, 0x88, 0x3f, 0x87, 0xaf, 0x5e, 0x1b, 0xd1, 0x99,
	0xfc, 0x70, 0x35, 0xff, 0x31, 0xdd, 0x96, 0xcf, 0x42, 0x16, 0x05, 0x3b, 0x4a, 0x6e, 0x1f, 0xba,
	0x44, 0x50, 0xaa, 0x5b, 0x23, 0x72, 0x7f, 0x15, 0xcd, 0x59, 0x04, 0x4c, 0x4a, 0xb5, 0xb6, 0xba,
	0x81, 0x4e, 0xc7, 0xf0, 0xb4, 0x7c, 0xb7, 0x07, 0xb8, 0x19, 0x98, 0x36, 0xb6, 0x48, 0x6e, 0xbe,
	0xd9, 0xec, 0x01, 0xe9, 0xd5, 0xe0, 0xf5, 0x38, 0x36, 0xd3, 0xc5, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7c, 0xe7, 0x68, 0x0e, 0xb3, 0x01, 0x00, 0x00,
}
