// Code generated by protoc-gen-go. DO NOT EDIT.
// source: options.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldOptions struct {
	LogField             string   `protobuf:"bytes,1,opt,name=logField,proto3" json:"logField,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldOptions) Reset()         { *m = FieldOptions{} }
func (m *FieldOptions) String() string { return proto.CompactTextString(m) }
func (*FieldOptions) ProtoMessage()    {}
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{0}
}

func (m *FieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions.Unmarshal(m, b)
}
func (m *FieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions.Marshal(b, m, deterministic)
}
func (m *FieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions.Merge(m, src)
}
func (m *FieldOptions) XXX_Size() int {
	return xxx_messageInfo_FieldOptions.Size(m)
}
func (m *FieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions proto.InternalMessageInfo

func (m *FieldOptions) GetLogField() string {
	if m != nil {
		return m.LogField
	}
	return ""
}

var E_Options = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldOptions)(nil),
	Field:         50000,
	Name:          "protocol.options",
	Tag:           "bytes,50000,opt,name=options",
	Filename:      "options.proto",
}

func init() {
	proto.RegisterType((*FieldOptions)(nil), "protocol.FieldOptions")
	proto.RegisterExtension(E_Options)
}

func init() {
	proto.RegisterFile("options.proto", fileDescriptor_110d40819f1994f9)
}

var fileDescriptor_110d40819f1994f9 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2f, 0x28, 0xc9,
	0xcc, 0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39,
	0x52, 0x0a, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x81, 0xa4, 0xd2, 0x34, 0xfd, 0x94,
	0xd4, 0xe2, 0xe4, 0xa2, 0xcc, 0x82, 0x92, 0xfc, 0x22, 0x88, 0x5a, 0x25, 0x2d, 0x2e, 0x1e, 0xb7,
	0xcc, 0xd4, 0x9c, 0x14, 0x7f, 0x88, 0x09, 0x42, 0x52, 0x5c, 0x1c, 0x39, 0xf9, 0xe9, 0x60, 0x21,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0xdf, 0x2a, 0x90, 0x8b, 0x1d, 0x6a, 0x91, 0x90,
	0xac, 0x1e, 0xc4, 0x64, 0x3d, 0x98, 0xc9, 0x7a, 0xc8, 0xa6, 0x48, 0x5c, 0x68, 0x63, 0x06, 0xea,
	0xe5, 0x36, 0x12, 0xd3, 0x83, 0x39, 0x05, 0x45, 0x3e, 0x08, 0x66, 0x8e, 0x13, 0x4f, 0x14, 0x97,
	0x9e, 0x35, 0x4c, 0x4d, 0x12, 0x1b, 0x98, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xbc,
	0x11, 0xf3, 0xd0, 0x00, 0x00, 0x00,
}
